### ISSUE TITLE
有没有安装文档,我安装不上去

### ISSUE THREAD

**Issue by Y-A-K-E** [hacfins/thinkphp6-api#1]
git clone后
用composer install 安装抛出异常,

```PHP Fatal error:  Uncaught Error: Call to undefined function yaconf() in C:\Users\xjw11\Documents\GitHub\thinkphp6-api\config\cache.php:9```

直接访问就是api抛出 500错误

**Comment by langyastudio** [comment]
安装时，将 yaconf() 临时改为 '' 即可
